"""Leakage-safe repeat-purchase and popularity retrieval baselines."""

from __future__ import annotations

import json
from collections.abc import Callable, Iterable
from dataclasses import asdict, dataclass
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from time import perf_counter
from typing import Any

from hm_recsys.data.io import TransactionEvent
from hm_recsys.evaluation.metrics import mean_average_precision_at_k, recall_at_k
from hm_recsys.evaluation.temporal import (
    TemporalSplit,
    TemporalSplitSummary,
    summarize_temporal_split_with_labels,
)


@dataclass
class ArticleStats:
    """Purchase count and recency statistics for ranking an article.

    Attributes:
        count: Number of observed purchases.
        last_seen: Most recent purchase date observed.
    """

    count: int = 0
    last_seen: date = date.min

    def update(self, seen_date: date) -> None:
        """Update count and recency with one observed purchase date.

        Args:
            seen_date: Date of the observed purchase.
        """

        self.count += 1
        if seen_date > self.last_seen:
            self.last_seen = seen_date


@dataclass(frozen=True)
class BaselineCandidateSources:
    """Reusable source rankings for repeat and popularity retrieval.

    Attributes:
        repeat_recommendations: Customer-specific repeat-purchase rankings.
        recent_popularity: Globally popular articles in the recent lookback.
        all_time_popularity: Globally popular articles across all pre-cutoff rows.
        customer_train_purchase_counts: Pre-cutoff purchase counts for target customers.
        train_rows_used: Number of pre-cutoff transaction rows consumed.
    """

    repeat_recommendations: dict[str, tuple[str, ...]]
    recent_popularity: tuple[str, ...]
    all_time_popularity: tuple[str, ...]
    customer_train_purchase_counts: dict[str, int]
    train_rows_used: int


@dataclass(frozen=True)
class BaselinePredictions:
    """Predictions and source lists generated by the baseline.

    Attributes:
        predictions: Final ranked article IDs per target customer.
        repeat_recommendations: Customer-specific repeat-purchase rankings.
        recent_popularity: Globally popular articles in the recent lookback.
        all_time_popularity: Globally popular articles across all pre-cutoff rows.
        customer_train_purchase_counts: Pre-cutoff purchase counts for target customers.
        train_rows_used: Number of pre-cutoff transaction rows consumed.
    """

    predictions: dict[str, tuple[str, ...]]
    repeat_recommendations: dict[str, tuple[str, ...]]
    recent_popularity: tuple[str, ...]
    all_time_popularity: tuple[str, ...]
    customer_train_purchase_counts: dict[str, int]
    train_rows_used: int


@dataclass(frozen=True)
class BaselineDiagnostics:
    """Aggregate diagnostics for baseline prediction quality and shape.

    Attributes:
        target_customers: Number of customers for whom predictions were generated.
        evaluated_customers: Number of customers scored in validation.
        customers_with_full_length_predictions: Rows with exactly ``k`` outputs.
        prediction_coverage: Share of target rows with exactly ``k`` outputs.
        duplicate_prediction_rows: Rows containing duplicate article IDs.
        average_prediction_count: Mean number of predictions per customer.
        predicted_article_coverage: Number of distinct articles recommended.
        repeat_source_customers: Customers with repeat-purchase candidates.
        recent_popularity_articles: Number of recent popularity candidates ranked.
        all_time_popularity_articles: Number of all-time popularity candidates ranked.
    """

    target_customers: int
    evaluated_customers: int
    customers_with_full_length_predictions: int
    prediction_coverage: float
    duplicate_prediction_rows: int
    average_prediction_count: float
    predicted_article_coverage: int
    repeat_source_customers: int
    recent_popularity_articles: int
    all_time_popularity_articles: int


@dataclass(frozen=True)
class BaselineEvaluationReport:
    """Evaluation report for the repeat-plus-popularity baseline.

    Attributes:
        generated_at_utc: UTC timestamp for the evaluation run.
        cutoff: Validation start date.
        validation_end_exclusive: Exclusive validation end date.
        horizon_days: Number of validation days.
        k: Recommendation list length used for scoring.
        popularity_lookback_days: Recent popularity lookback length.
        map_at_k: Mean average precision at ``k``.
        recall_at_k: Mean recall at ``k``.
        runtime_seconds: Wall-clock runtime for evaluation.
        diagnostics: Prediction shape and coverage diagnostics.
        split_summary: Temporal split row/customer/article counts.
    """

    generated_at_utc: str
    cutoff: str
    validation_end_exclusive: str
    horizon_days: int
    k: int
    popularity_lookback_days: int
    map_at_k: float
    recall_at_k: float
    runtime_seconds: float
    diagnostics: BaselineDiagnostics
    split_summary: TemporalSplitSummary


@dataclass(frozen=True)
class BaselineSubmissionPredictions:
    """Final-data baseline predictions for Kaggle submission generation.

    Attributes:
        predictions: Per-customer ranked recommendations and source lists.
        max_transaction_date: Latest transaction date observed in training data.
        training_cutoff: Exclusive cutoff used by the baseline builder; equal to
            ``max_transaction_date + 1 day`` for final submission generation.
        runtime_seconds: Wall-clock runtime for the two-pass generation.
        diagnostics: Prediction shape diagnostics across the submission universe.
    """

    predictions: BaselinePredictions
    max_transaction_date: date
    training_cutoff: date
    runtime_seconds: float
    diagnostics: BaselineDiagnostics


def build_repeat_popularity_baseline(
    transactions: Iterable[TransactionEvent],
    split: TemporalSplit,
    target_customer_ids: Iterable[str],
    k: int = 12,
    popularity_lookback_days: int = 7,
) -> BaselinePredictions:
    """Build repeat-purchase recommendations with popularity backfill.

    Only transactions before ``split.cutoff`` are used, so the builder is safe for
    next-7-day validation.

    Args:
        transactions: Transaction events in any iterable order.
        split: Temporal split defining the training cutoff.
        target_customer_ids: Customers requiring predictions.
        k: Maximum number of predictions per customer.
        popularity_lookback_days: Number of days before cutoff used for recent
            popularity.

    Returns:
        Baseline predictions and ranked source lists.

    Raises:
        ValueError: If ``k`` or ``popularity_lookback_days`` is not positive.
    """

    if k <= 0:
        raise ValueError("k must be positive")
    if popularity_lookback_days <= 0:
        raise ValueError("popularity_lookback_days must be positive")

    target_customer_tuple = tuple(target_customer_ids)
    sources = build_repeat_popularity_candidate_sources(
        transactions=transactions,
        split=split,
        target_customer_ids=target_customer_tuple,
        k=k,
        popularity_lookback_days=popularity_lookback_days,
    )
    popularity_backfill = merge_ranked_sources(
        (sources.recent_popularity, sources.all_time_popularity), k=k
    )
    predictions = {
        customer_id: merge_ranked_sources(
            (sources.repeat_recommendations.get(customer_id, ()), popularity_backfill), k=k
        )
        for customer_id in sorted(target_customer_tuple)
    }
    return BaselinePredictions(
        predictions=predictions,
        repeat_recommendations=sources.repeat_recommendations,
        recent_popularity=sources.recent_popularity,
        all_time_popularity=sources.all_time_popularity,
        customer_train_purchase_counts=sources.customer_train_purchase_counts,
        train_rows_used=sources.train_rows_used,
    )


def build_repeat_popularity_candidate_sources(
    transactions: Iterable[TransactionEvent],
    split: TemporalSplit,
    target_customer_ids: Iterable[str],
    k: int = 12,
    popularity_lookback_days: int = 7,
) -> BaselineCandidateSources:
    """Build source rankings without materializing final predictions per customer.

    Args:
        transactions: Transaction events in any iterable order.
        split: Temporal split defining the training cutoff.
        target_customer_ids: Customers for whom repeat-history sources are needed.
        k: Maximum per-customer repeat ranking depth.
        popularity_lookback_days: Number of days before cutoff used for recent
            popularity.

    Returns:
        Repeat and popularity source rankings plus training counts.

    Raises:
        ValueError: If ``k`` or ``popularity_lookback_days`` is not positive.
    """

    if k <= 0:
        raise ValueError("k must be positive")
    if popularity_lookback_days <= 0:
        raise ValueError("popularity_lookback_days must be positive")

    target_customer_set = set(target_customer_ids)
    recent_start = split.cutoff - timedelta(days=popularity_lookback_days)
    recent_popularity_stats: dict[str, ArticleStats] = {}
    all_time_popularity_stats: dict[str, ArticleStats] = {}
    repeat_stats: dict[str, dict[str, ArticleStats]] = {}
    customer_train_purchase_counts: dict[str, int] = {}
    train_rows_used = 0

    for transaction in transactions:
        if transaction.t_dat >= split.cutoff:
            continue
        train_rows_used += 1
        _update_article_stats(all_time_popularity_stats, transaction.article_id, transaction.t_dat)
        if transaction.t_dat >= recent_start:
            _update_article_stats(
                recent_popularity_stats, transaction.article_id, transaction.t_dat
            )
        if transaction.customer_id in target_customer_set:
            customer_train_purchase_counts[transaction.customer_id] = (
                customer_train_purchase_counts.get(transaction.customer_id, 0) + 1
            )
            customer_stats = repeat_stats.setdefault(transaction.customer_id, {})
            _update_article_stats(customer_stats, transaction.article_id, transaction.t_dat)

    recent_popularity = rank_article_stats(
        recent_popularity_stats, limit=max(k, len(recent_popularity_stats))
    )
    all_time_popularity = rank_article_stats(
        all_time_popularity_stats, limit=max(k, len(all_time_popularity_stats))
    )
    repeat_recommendations = {
        customer_id: rank_article_stats(article_stats, limit=k)
        for customer_id, article_stats in repeat_stats.items()
    }
    return BaselineCandidateSources(
        repeat_recommendations=repeat_recommendations,
        recent_popularity=recent_popularity,
        all_time_popularity=all_time_popularity,
        customer_train_purchase_counts=customer_train_purchase_counts,
        train_rows_used=train_rows_used,
    )


def evaluate_repeat_popularity_baseline(
    transaction_iter_factory: Callable[[], Iterable[TransactionEvent]],
    split: TemporalSplit,
    target_customer_ids: Iterable[str] | None = None,
    k: int = 12,
    popularity_lookback_days: int = 7,
) -> BaselineEvaluationReport:
    """Evaluate the repeat-plus-popularity baseline on a temporal split.

    Args:
        transaction_iter_factory: Callable returning a fresh transaction iterable
            for each pass over the data.
        split: Temporal split defining train and validation windows.
        target_customer_ids: Customer universe requiring predictions. Pass the
            ``sample_submission.csv`` customer IDs for Kaggle-like diagnostics.
            When omitted, only validation-label customers receive predictions.
        k: Recommendation list length and MAP/recall depth.
        popularity_lookback_days: Recent popularity lookback length.

    Returns:
        Structured evaluation report with MAP@K, recall@K, diagnostics, and split
        summary.
    """

    started_at = perf_counter()
    validation_data = summarize_temporal_split_with_labels(transaction_iter_factory(), split)
    target_customer_set = (
        set(target_customer_ids)
        if target_customer_ids is not None
        else set(validation_data.validation_labels)
    )
    labels = {
        customer_id: articles
        for customer_id, articles in validation_data.validation_labels.items()
        if customer_id in target_customer_set
    }
    baseline = build_repeat_popularity_baseline(
        transactions=transaction_iter_factory(),
        split=split,
        target_customer_ids=target_customer_set,
        k=k,
        popularity_lookback_days=popularity_lookback_days,
    )
    predictions = baseline.predictions
    map_score = mean_average_precision_at_k(labels, predictions, k=k)
    recall_score = _mean_recall_at_k(labels, predictions, k=k)
    diagnostics = build_baseline_diagnostics(
        baseline=baseline,
        evaluated_customer_count=len(labels),
        k=k,
    )
    return BaselineEvaluationReport(
        generated_at_utc=datetime.now(UTC).isoformat(timespec="seconds"),
        cutoff=split.cutoff.isoformat(),
        validation_end_exclusive=split.validation_end.isoformat(),
        horizon_days=split.horizon_days,
        k=k,
        popularity_lookback_days=popularity_lookback_days,
        map_at_k=map_score,
        recall_at_k=recall_score,
        runtime_seconds=perf_counter() - started_at,
        diagnostics=diagnostics,
        split_summary=validation_data.summary,
    )


def build_repeat_popularity_submission_baseline(
    transaction_iter_factory: Callable[[], Iterable[TransactionEvent]],
    target_customer_ids: Iterable[str],
    k: int = 12,
    popularity_lookback_days: int = 7,
) -> BaselineSubmissionPredictions:
    """Build repeat-plus-popularity predictions for final Kaggle submission.

    This uses all transactions in ``transactions_train.csv`` by setting the
    internal cutoff to one day after the maximum transaction date. The resulting
    predictions are for the customer universe supplied by ``sample_submission``.

    Args:
        transaction_iter_factory: Callable returning a fresh transaction iterable
            for each pass over the data.
        target_customer_ids: Customer IDs requiring predictions.
        k: Maximum number of predictions per customer.
        popularity_lookback_days: Number of final training days used for recent
            popularity.

    Returns:
        Final-data baseline predictions plus metadata and diagnostics.

    Raises:
        ValueError: If no transactions are available or baseline parameters are
        invalid.
    """

    started_at = perf_counter()
    target_customer_tuple = tuple(target_customer_ids)
    max_transaction_date = find_max_transaction_date(transaction_iter_factory())
    training_cutoff = max_transaction_date + timedelta(days=1)
    split = TemporalSplit(cutoff=training_cutoff, horizon_days=7)
    predictions = build_repeat_popularity_baseline(
        transactions=transaction_iter_factory(),
        split=split,
        target_customer_ids=target_customer_tuple,
        k=k,
        popularity_lookback_days=popularity_lookback_days,
    )
    diagnostics = build_baseline_diagnostics(
        baseline=predictions,
        evaluated_customer_count=0,
        k=k,
    )
    return BaselineSubmissionPredictions(
        predictions=predictions,
        max_transaction_date=max_transaction_date,
        training_cutoff=training_cutoff,
        runtime_seconds=perf_counter() - started_at,
        diagnostics=diagnostics,
    )


def find_max_transaction_date(transactions: Iterable[TransactionEvent]) -> date:
    """Find the latest transaction date in an iterable of events.

    Args:
        transactions: Transaction events to scan.

    Returns:
        Maximum observed transaction date.

    Raises:
        ValueError: If ``transactions`` is empty.
    """

    max_date: date | None = None
    for transaction in transactions:
        max_date = transaction.t_dat if max_date is None else max(max_date, transaction.t_dat)
    if max_date is None:
        raise ValueError("cannot build a submission baseline without transactions")
    return max_date


def rank_article_stats(stats: dict[str, ArticleStats], limit: int) -> tuple[str, ...]:
    """Rank articles by frequency, recency, and ID tie-break.

    Args:
        stats: Article statistics keyed by article ID.
        limit: Maximum number of article IDs to return.

    Returns:
        Ranked article ID tuple.
    """

    ranked = sorted(
        stats.items(),
        key=lambda item: (-item[1].count, -item[1].last_seen.toordinal(), item[0]),
    )
    return tuple(article_id for article_id, _ in ranked[:limit])


def build_baseline_diagnostics(
    baseline: BaselinePredictions,
    evaluated_customer_count: int,
    k: int,
) -> BaselineDiagnostics:
    """Build aggregate diagnostics for baseline predictions.

    Args:
        baseline: Baseline predictions and source lists.
        evaluated_customer_count: Number of customers evaluated by metrics.
        k: Expected prediction count per customer.

    Returns:
        Aggregate diagnostics for coverage, duplicates, and source availability.
    """

    prediction_lengths = [len(predictions) for predictions in baseline.predictions.values()]
    duplicate_rows = sum(
        1
        for predictions in baseline.predictions.values()
        if len(set(predictions)) != len(predictions)
    )
    predicted_articles = {
        article_id for predictions in baseline.predictions.values() for article_id in predictions
    }
    full_length_rows = sum(1 for length in prediction_lengths if length == k)
    average_prediction_count = (
        sum(prediction_lengths) / len(prediction_lengths) if prediction_lengths else 0.0
    )
    return BaselineDiagnostics(
        target_customers=len(baseline.predictions),
        evaluated_customers=evaluated_customer_count,
        customers_with_full_length_predictions=full_length_rows,
        prediction_coverage=(
            full_length_rows / len(baseline.predictions) if baseline.predictions else 0.0
        ),
        duplicate_prediction_rows=duplicate_rows,
        average_prediction_count=average_prediction_count,
        predicted_article_coverage=len(predicted_articles),
        repeat_source_customers=len(baseline.repeat_recommendations),
        recent_popularity_articles=len(baseline.recent_popularity),
        all_time_popularity_articles=len(baseline.all_time_popularity),
    )


def baseline_evaluation_report_to_dict(report: BaselineEvaluationReport) -> dict[str, Any]:
    """Convert a baseline evaluation report to serializable primitives.

    Args:
        report: Report object to convert.

    Returns:
        Dictionary suitable for JSON serialization.
    """

    return asdict(report)


def write_baseline_evaluation_report(report: BaselineEvaluationReport, path: Path | str) -> Path:
    """Write a baseline evaluation report as deterministic JSON.

    Args:
        report: Evaluation report to serialize.
        path: Destination JSON path.

    Returns:
        Resolved path written to disk.
    """

    report_path = Path(path).expanduser().resolve()
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(baseline_evaluation_report_to_dict(report), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return report_path


def _update_article_stats(stats: dict[str, ArticleStats], article_id: str, seen_date: date) -> None:
    """Update article statistics for one observed purchase event."""

    article_stats = stats.setdefault(article_id, ArticleStats())
    article_stats.update(seen_date)


def merge_ranked_sources(sources: Iterable[Iterable[str]], k: int) -> tuple[str, ...]:
    """Merge ranked candidate sources with duplicate suppression.

    Args:
        sources: Ranked candidate iterables in priority order.
        k: Maximum merged output length.

    Returns:
        Tuple of up to ``k`` unique article IDs.
    """

    merged: list[str] = []
    seen: set[str] = set()
    for source in sources:
        for article_id in source:
            if article_id in seen:
                continue
            merged.append(article_id)
            seen.add(article_id)
            if len(merged) == k:
                return tuple(merged)
    return tuple(merged)


def _mean_recall_at_k(
    actual_by_customer: dict[str, tuple[str, ...]],
    predicted_by_customer: dict[str, tuple[str, ...]],
    k: int,
) -> float:
    """Compute mean recall@K across validation customers.

    Args:
        actual_by_customer: Relevant article IDs by customer.
        predicted_by_customer: Ranked predictions by customer.
        k: Maximum rank depth.

    Returns:
        Mean recall@K, or ``0.0`` when no customers are provided.
    """

    scores = [
        recall_at_k(actual, predicted_by_customer.get(customer_id, ()), k=k)
        for customer_id, actual in actual_by_customer.items()
    ]
    return sum(scores) / len(scores) if scores else 0.0
