"""Canonical retrieval source names used across diagnostics and exports."""

REPEAT_SOURCE = "repeat"
RECENT_POPULARITY_SOURCE = "recent_popularity"
ALL_TIME_POPULARITY_SOURCE = "all_time_popularity"
AGE_SEGMENT_POPULARITY_SOURCE = "age_segment_popularity"
GARMENT_GROUP_POPULARITY_SOURCE = "garment_group_popularity"
REPEAT_POPULARITY_BLEND_SOURCE = "repeat_popularity_blend"
CO_VISITATION_SOURCE = "co_visitation"
TEXT_SIMILARITY_SOURCE = "text_similarity"
IMAGE_SIMILARITY_SOURCE = "image_similarity"
MULTIMODAL_SIMILARITY_SOURCE = "multimodal_similarity"
MULTIMODAL_SIMILARITY_POPULARITY_PRIOR_SOURCE = "multimodal_similarity_popularity_prior"
TWO_TOWER_MULTIMODAL_SOURCE = "two_tower_multimodal"
REPEAT_CO_VISITATION_POPULARITY_BLEND_SOURCE = "repeat_co_visitation_popularity_blend"
REPEAT_POPULARITY_CO_VISITATION_BLEND_SOURCE = "repeat_popularity_co_visitation_blend"
